#ifndef DELAYED_ACTION_TYPE_ENUM_HPP
#define DELAYED_ACTION_TYPE_ENUM_HPP

namespace network
{
    enum delayed_action_type_enum
    {
        DELAYED_ACTION_DISCONNECT = 0,
        DELAYED_ACTION_OBJECT_USE = 1,
        DELAYED_ACTION_JOIN_CHARACTER = 2,
        DELAYED_ACTION_AGGRESSION_IMMUNE = 3
    };
}

#endif // DELAYED_ACTION_TYPE_ENUM_HPP