#ifndef NUMERICAL_VALUE_TYPE_ENUM_HPP
#define NUMERICAL_VALUE_TYPE_ENUM_HPP

namespace network
{
    enum numerical_value_type_enum
    {
        NUMERICAL_VALUE_DEFAULT = 0,
        NUMERICAL_VALUE_COLLECT = 1,
        NUMERICAL_VALUE_CRAFT = 2,
        NUMERICAL_VALUE_PADDOCK = 3,
        NUMERICAL_VALUE_RED = 64,
        NUMERICAL_VALUE_BLUE = 65,
        NUMERICAL_VALUE_GREEN = 66
    };
}

#endif // NUMERICAL_VALUE_TYPE_ENUM_HPP