#ifndef PRISM_SET_SABOTAGED_REFUSED_REASON_ENUM_HPP
#define PRISM_SET_SABOTAGED_REFUSED_REASON_ENUM_HPP

namespace network
{
    enum prism_set_sabotaged_refused_reason_enum
    {
        SABOTAGE_INSUFFICIENT_RIGHTS = 0,
        SABOTAGE_MEMBER_ACCOUNT_NEEDED = 1,
        SABOTAGE_RESTRICTED_ACCOUNT = 2,
        SABOTAGE_WRONG_ALLIANCE = 3,
        SABOTAGE_NO_PRISM = 4,
        SABOTAGE_WRONG_STATE = 5
    };
}

#endif // PRISM_SET_SABOTAGED_REFUSED_REASON_ENUM_HPP