#ifndef SOCIAL_GROUP_INVITATION_STATE_ENUM_HPP
#define SOCIAL_GROUP_INVITATION_STATE_ENUM_HPP

namespace network
{
    enum social_group_invitation_state_enum
    {
        SOCIAL_GROUP_INVITATION_FAILED = 0,
        SOCIAL_GROUP_INVITATION_SENT = 1,
        SOCIAL_GROUP_INVITATION_CANCELED = 2,
        SOCIAL_GROUP_INVITATION_OK = 3
    };
}

#endif // SOCIAL_GROUP_INVITATION_STATE_ENUM_HPP