#ifndef SUB_ENTITY_BINDING_POINT_CATEGORY_ENUM_HPP
#define SUB_ENTITY_BINDING_POINT_CATEGORY_ENUM_HPP

namespace network
{
    enum sub_entity_binding_point_category_enum
    {
        HOOK_POINT_CATEGORY_UNUSED = 0,
        HOOK_POINT_CATEGORY_PET = 1,
        HOOK_POINT_CATEGORY_MOUNT_DRIVER = 2,
        HOOK_POINT_CATEGORY_LIFTED_ENTITY = 3,
        HOOK_POINT_CATEGORY_BASE_BACKGROUND = 4,
        HOOK_POINT_CATEGORY_MERCHANT_BAG = 5,
        HOOK_POINT_CATEGORY_BASE_FOREGROUND = 6
    };
}

#endif // SUB_ENTITY_BINDING_POINT_CATEGORY_ENUM_HPP